---
- name: Check prerequisites for an OCP IPI installation on Nutanix
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  vars_files:
    - secret.yml
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_central_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: true

  tasks:
    - name: Ensure ccoctl is correctly installed in the host machine
      block:
        - name: Checking if ccoctl utility is installed
          stat:
            path: "/usr/bin/ccoctl"
          register: ccoctl_check
        - name: Print informative message if ccoctl utility is not found or not executable
          fail:
            msg: "ccoctl utility does not exist or is not executable. Please install and configure it appropriately.
                  https://docs.openshift.com/container-platform/4.13/installing/installing_nutanix/preparing-to-install-on-nutanix.html#cco-ccoctl-configuring_preparing-to-install-on-nutanix"
          when: not (ccoctl_check.stat.exists and ccoctl_check.stat.executable)

    - name: Ensure port 9440 of Prism Central and Prism Element are open
      wait_for:
        host: "{{ item }}"
        port: 9440
        state: started
        delay: 0
        timeout: 3
      loop:
        - "{{ nutanix_central_host }}"
        - "{{ nutanix_element_host }}"

    - name: Ensure SSL certificate is valid
      uri:
        url: "https://{{ nutanix_central_host }}:9440"
        validate_certs: true

#    - name: Ensure user has enough privileges TODO

#    - name: Ensure cluster AOS version is compatible
#
#    - name: Ensure Prism Central version is compatible
#
#    - name: Ensure cluster has enough storage capacity
#
#    - name: Ensure DNS entries are set
