---
- name: Check prerequisites for an OCP IPI installation on Nutanix
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  vars_files:
    - secret.yml
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_central_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: true

  tasks:
    - name: Ensure ccoctl is correctly installed in the host machine
      block:
        - name: Checking if ccoctl utility is installed
          stat:
            path: "/usr/bin/ccoctl"
          register: ccoctl_check
        - name: Print informative message if ccoctl utility is not found or not executable
          fail:
            msg: "ccoctl utility does not exist or is not executable. Please install and configure it appropriately.
                  https://docs.openshift.com/container-platform/4.13/installing/installing_nutanix/preparing-to-install-on-nutanix.html#cco-ccoctl-configuring_preparing-to-install-on-nutanix"
          when: not (ccoctl_check.stat.exists and ccoctl_check.stat.executable)

    - name: Ensure port 9440 of Prism Central and Prism Element are open
      wait_for:
        host: "{{ item }}"
        port: 9440
        state: started
        delay: 0
        timeout: 3
      loop:
        - "{{ nutanix_central_host }}"
        - "{{ nutanix_element_host }}"

    - name: Ensure SSL certificate is valid
      uri:
        url: "https://{{ nutanix_central_host }}:9440"
        validate_certs: true

    # As for now (summer 2023), https://github.com/nutanix/nutanix.ansible doesn't allow accessing user's permissions
    # Furthermore, the Prism Central v3 API doesn't allow too, or at least not easily
    # That is, to ensure the provided account has enough permissions, this task runs CRUD operations on mock VMs, categories and images
    # The OCP IPI installation needs to perform these actions
    # TODO find a better solution
    - name: Ensure account has enough permissions
      block:
        - name: "Ensure that the account can perform CRUD operations on VMs in the cluster {{ nutanix_cluster }}"
          block:
            - name: Ensure that the account can create a VM in the cluster
              ntnx_vms:
                state: present
                name: tmp_ansible_check_ipi_prerequisites
                desc: Temporary VM created by a Ansible playbook to check if OCP IPI installation prerequisites are fulfilled
                cluster:
                  name: "{{ nutanix_cluster }}"
                vcpus: 1
                cores_per_vcpu: 1
                memory_gb: 1
              register: created_vm

            - name: Ensure that the account can list its VM in the cluster
              ntnx_vms_info:
                filter:
                  vm_name: tmp_ansible_check_ipi_prerequisites
                kind: vm
              register: vm_info
              failed_when: vm_info.response.metadata.total_matches != 1

            - name: Ensure that the account can update its VM in the cluster
              ntnx_vms:
                vm_uuid: "{{created_vm.vm_uuid}}"
                memory_gb: 2

            - name: Ensure that the account can delete its VM in the cluster
              ntnx_vms:
                state: absent
                vm_uuid: "{{created_vm.vm_uuid}}"

#        - name: "Ensure that the account can perform CRUD operations on categories in the cluster {{ nutanix_element_host }}"
#
#        - name: "Ensure that the account can perform CRUD operations on images in the cluster {{ nutanix_element_host }}"


#    - name: Ensure cluster AOS version is compatible
#
#    - name: Ensure Prism Central version is compatible
#
#    - name: Ensure cluster has enough storage capacity
#
#    - name: Ensure DNS entries are set
